import { freezeRtcRuntimeValue } from './runtime-freeze.js';

export const RTC_LOOKUP_HELPER_NAMING_PROFILE_TERMS = freezeRtcRuntimeValue(['lower-camel-rtc', 'upper-camel-rtc', 'snake-case-rtc'] as const);

export const RTC_LOOKUP_HELPER_NAMING_FAMILY_TERMS = freezeRtcRuntimeValue(['provider-catalog-by-provider-key', 'provider-package-by-provider-key', 'provider-package-by-package-identity', 'provider-activation-by-provider-key', 'capability-catalog', 'capability-descriptor-by-capability-key', 'provider-extension-catalog', 'provider-extension-descriptor-by-extension-key', 'provider-extensions-for-provider', 'provider-extensions-by-extension-keys', 'provider-extension-membership', 'language-workspace-by-language', 'provider-url-parser', 'provider-selection-resolver', 'provider-support-status-resolver', 'provider-support-state-factory', 'provider-package-loader-factory', 'provider-package-load-target-resolver', 'provider-module-loader', 'single-provider-package-installer', 'batch-provider-package-installer'] as const);

export const RTC_LOOKUP_HELPER_NAMING_STANDARD = freezeRtcRuntimeValue({
  profileTerms: RTC_LOOKUP_HELPER_NAMING_PROFILE_TERMS,
  familyTerms: RTC_LOOKUP_HELPER_NAMING_FAMILY_TERMS,
  profiles: freezeRtcRuntimeValue({
  "lower-camel-rtc": freezeRtcRuntimeValue({
    languages: freezeRtcRuntimeValue(['typescript', 'flutter', 'java', 'swift', 'kotlin'] as const),
    helpers: freezeRtcRuntimeValue({
  "providerCatalogByProviderKey": 'getRtcProviderByProviderKey',
  "providerPackageByProviderKey": 'getRtcProviderPackageByProviderKey',
  "providerPackageByPackageIdentity": 'getRtcProviderPackageByPackageIdentity',
  "providerActivationByProviderKey": 'getRtcProviderActivationByProviderKey',
  "capabilityCatalog": 'getRtcCapabilityCatalog',
  "capabilityDescriptorByCapabilityKey": 'getRtcCapabilityDescriptor',
  "providerExtensionCatalog": 'getRtcProviderExtensionCatalog',
  "providerExtensionDescriptorByExtensionKey": 'getRtcProviderExtensionDescriptor',
  "providerExtensionsForProvider": 'getRtcProviderExtensionsForProvider',
  "providerExtensionsByExtensionKeys": 'getRtcProviderExtensions',
  "providerExtensionMembership": 'hasRtcProviderExtension',
  "languageWorkspaceByLanguage": 'getRtcLanguageWorkspaceByLanguage',
  "providerUrlParser": 'parseRtcProviderUrl',
  "providerSelectionResolver": 'resolveRtcProviderSelection',
  "providerSupportStatusResolver": 'resolveRtcProviderSupportStatus',
  "providerSupportStateFactory": 'createRtcProviderSupportState',
  "providerPackageLoaderFactory": 'createRtcProviderPackageLoader',
  "providerPackageLoadTargetResolver": 'resolveRtcProviderPackageLoadTarget',
  "providerModuleLoader": 'loadRtcProviderModule',
  "singleProviderPackageInstaller": 'installRtcProviderPackage',
  "batchProviderPackageInstaller": 'installRtcProviderPackages',
} as const),
  } as const),
  "upper-camel-rtc": freezeRtcRuntimeValue({
    languages: freezeRtcRuntimeValue(['csharp', 'go'] as const),
    helpers: freezeRtcRuntimeValue({
  "providerCatalogByProviderKey": 'GetRtcProviderByProviderKey',
  "providerPackageByProviderKey": 'GetRtcProviderPackageByProviderKey',
  "providerPackageByPackageIdentity": 'GetRtcProviderPackageByPackageIdentity',
  "providerActivationByProviderKey": 'GetRtcProviderActivationByProviderKey',
  "capabilityCatalog": 'GetRtcCapabilityCatalog',
  "capabilityDescriptorByCapabilityKey": 'GetRtcCapabilityDescriptor',
  "providerExtensionCatalog": 'GetRtcProviderExtensionCatalog',
  "providerExtensionDescriptorByExtensionKey": 'GetRtcProviderExtensionDescriptor',
  "providerExtensionsForProvider": 'GetRtcProviderExtensionsForProvider',
  "providerExtensionsByExtensionKeys": 'GetRtcProviderExtensions',
  "providerExtensionMembership": 'HasRtcProviderExtension',
  "languageWorkspaceByLanguage": 'GetRtcLanguageWorkspaceByLanguage',
  "providerUrlParser": 'ParseRtcProviderUrl',
  "providerSelectionResolver": 'ResolveRtcProviderSelection',
  "providerSupportStatusResolver": 'ResolveRtcProviderSupportStatus',
  "providerSupportStateFactory": 'CreateRtcProviderSupportState',
  "providerPackageLoaderFactory": 'CreateRtcProviderPackageLoader',
  "providerPackageLoadTargetResolver": 'ResolveRtcProviderPackageLoadTarget',
  "providerModuleLoader": 'LoadRtcProviderModule',
  "singleProviderPackageInstaller": 'InstallRtcProviderPackage',
  "batchProviderPackageInstaller": 'InstallRtcProviderPackages',
} as const),
  } as const),
  "snake-case-rtc": freezeRtcRuntimeValue({
    languages: freezeRtcRuntimeValue(['rust', 'python'] as const),
    helpers: freezeRtcRuntimeValue({
  "providerCatalogByProviderKey": 'get_rtc_provider_by_provider_key',
  "providerPackageByProviderKey": 'get_rtc_provider_package_by_provider_key',
  "providerPackageByPackageIdentity": 'get_rtc_provider_package_by_package_identity',
  "providerActivationByProviderKey": 'get_rtc_provider_activation_by_provider_key',
  "capabilityCatalog": 'get_rtc_capability_catalog',
  "capabilityDescriptorByCapabilityKey": 'get_rtc_capability_descriptor',
  "providerExtensionCatalog": 'get_rtc_provider_extension_catalog',
  "providerExtensionDescriptorByExtensionKey": 'get_rtc_provider_extension_descriptor',
  "providerExtensionsForProvider": 'get_rtc_provider_extensions_for_provider',
  "providerExtensionsByExtensionKeys": 'get_rtc_provider_extensions',
  "providerExtensionMembership": 'has_rtc_provider_extension',
  "languageWorkspaceByLanguage": 'get_rtc_language_workspace_by_language',
  "providerUrlParser": 'parse_rtc_provider_url',
  "providerSelectionResolver": 'resolve_rtc_provider_selection',
  "providerSupportStatusResolver": 'resolve_rtc_provider_support_status',
  "providerSupportStateFactory": 'create_rtc_provider_support_state',
  "providerPackageLoaderFactory": 'create_rtc_provider_package_loader',
  "providerPackageLoadTargetResolver": 'resolve_rtc_provider_package_load_target',
  "providerModuleLoader": 'load_rtc_provider_module',
  "singleProviderPackageInstaller": 'install_rtc_provider_package',
  "batchProviderPackageInstaller": 'install_rtc_provider_packages',
} as const),
  } as const),
  } as const),
} as const);
