using System.Collections.Generic;
using System.Linq;

namespace Sdkwork.Rtc.Sdk;

public sealed record RtcLanguageWorkspaceCatalogEntry(
    string language,
    string workspace,
    string displayName,
    string publicPackage,
    string maturityTier,
    bool controlSdk,
    bool runtimeBridge,
    string currentRole,
    string workspaceSummary,
    IReadOnlyList<string> roleHighlights
);

public static class RtcLanguageWorkspaceCatalog
{
    public static readonly IReadOnlyList<RtcLanguageWorkspaceCatalogEntry> Entries =
    [
        new("typescript", "sdkwork-rtc-sdk-typescript", "TypeScript", "@sdkwork/rtc-sdk", "reference", true, true, "Executable reference implementation", "This workspace is the executable reference implementation for provider-neutral RTC contracts, JDBC-style driver selection, standardized runtime lifecycle delegation, and provider package boundaries in sdkwork-rtc-sdk.", new List<string> { "provider-neutral RTC contracts", "JDBC-style driver and data-source model", "assembly-driven provider catalog at src/provider-catalog.ts", "assembly-driven capability catalog at src/capability-catalog.ts with required-baseline and optional-advanced surface descriptors", "assembly-driven provider extension catalog at src/provider-extension-catalog.ts with unwrap-only extension metadata", "surface-aware capability negotiation and degradation helpers with supported, degraded, and unsupported outcomes", "stable runtime bridge contract methods join, leave, publish, unpublish, muteAudio, and muteVideo", "explicit native_sdk_not_available failure when no runtime bridge is registered", "assembly-driven default provider constants DEFAULT_RTC_PROVIDER_KEY, DEFAULT_RTC_PROVIDER_PLUGIN_ID, and DEFAULT_RTC_PROVIDER_DRIVER_ID", "built-in provider adapters for volcengine, aliyun, and tencent", "TypeScript provider package statuses standardize built-in root-public packages as root_public_reference_boundary and executable non-builtin packages as package_reference_boundary", "TypeScript runtime bridge baseline reference-baseline with official vendor SDK requirement required" }),
        new("flutter", "sdkwork-rtc-sdk-flutter", "Flutter", "rtc_sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is materialized now so the official language matrix stays explicit and verifiable. Future Flutter runtime bridge work must follow the same provider-adapter and capability standards as the TypeScript baseline.", new List<string> { "provider metadata, capability matrix, and driver selection standards", "reserved Flutter language boundary with no runtime bridge claim in the current landing", "future Flutter runtime bridge work must follow the TypeScript baseline contract", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("rust", "sdkwork-rtc-sdk-rust", "Rust", "rtc_sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Rust standard boundary for provider metadata, selection, and future control-plane integration.", new List<string> { "provider metadata and driver selection standards", "reserved Rust workspace boundary for control-plane expansion", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("java", "sdkwork-rtc-sdk-java", "Java", "com.sdkwork:rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Java standard boundary for provider metadata, driver selection, and future enterprise runtime integration.", new List<string> { "provider metadata and driver selection standards", "reserved Java language boundary for future enterprise runtime integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("csharp", "sdkwork-rtc-sdk-csharp", "C#", "Sdkwork.Rtc.Sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved C# standard boundary for provider metadata, driver selection, and future desktop or server-side control integration.", new List<string> { "provider metadata and driver selection standards", "reserved C# language boundary for desktop or server-side control integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("swift", "sdkwork-rtc-sdk-swift", "Swift", "RtcSdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Swift standard boundary for provider metadata, driver selection, and future iOS or macOS runtime bridge integration.", new List<string> { "provider metadata and driver selection standards", "reserved Swift language boundary for iOS or macOS runtime bridge integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("kotlin", "sdkwork-rtc-sdk-kotlin", "Kotlin", "com.sdkwork:rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Kotlin standard boundary for provider metadata, driver selection, and future Android runtime bridge integration.", new List<string> { "provider metadata and driver selection standards", "reserved Kotlin language boundary for Android runtime bridge integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("go", "sdkwork-rtc-sdk-go", "Go", "github.com/sdkwork/rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Go standard boundary for provider metadata, driver selection, and future control-plane tooling integration.", new List<string> { "provider metadata and driver selection standards", "reserved Go language boundary for control-plane tooling integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
        new("python", "sdkwork-rtc-sdk-python", "Python", "sdkwork-rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Python standard boundary for provider metadata, driver selection, and future automation or control-plane integration.", new List<string> { "provider metadata and driver selection standards", "reserved Python language boundary for automation or control-plane integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, provider support, and provider package loader boundaries before runtime bridge landing" }),
    ];

public static RtcLanguageWorkspaceCatalogEntry? GetRtcLanguageWorkspaceByLanguage(string language) =>
        Entries.FirstOrDefault(entry => entry.language == language);

}
