package com.sdkwork.rtc.metadata

data class RtcLanguageWorkspaceCatalogEntry(
    val language: String,
    val workspace: String,
    val displayName: String,
    val publicPackage: String,
    val maturityTier: String,
    val controlSdk: Boolean,
    val runtimeBridge: Boolean,
    val currentRole: String,
    val workspaceSummary: String,
    val roleHighlights: List<String>,
)

object RtcLanguageWorkspaceCatalog {
    val entries: List<RtcLanguageWorkspaceCatalogEntry> = listOf(
        RtcLanguageWorkspaceCatalogEntry("typescript", "sdkwork-rtc-sdk-typescript", "TypeScript", "@sdkwork/rtc-sdk", "reference", true, true, "Executable reference implementation", "This workspace is the executable reference implementation for provider-neutral RTC contracts, JDBC-style driver selection, standardized runtime lifecycle delegation, and provider package boundaries in sdkwork-rtc-sdk.", listOf("provider-neutral RTC contracts", "JDBC-style driver and data-source model", "assembly-driven provider catalog at src/provider-catalog.ts", "assembly-driven capability catalog at src/capability-catalog.ts with required-baseline and optional-advanced surface descriptors", "assembly-driven provider extension catalog at src/provider-extension-catalog.ts with unwrap-only extension metadata", "surface-aware capability negotiation and degradation helpers with supported, degraded, and unsupported outcomes", "stable runtime bridge contract methods join, leave, publish, unpublish, muteAudio, and muteVideo", "explicit native_sdk_not_available failure when no runtime bridge is registered", "assembly-driven default provider constants DEFAULT_RTC_PROVIDER_KEY, DEFAULT_RTC_PROVIDER_PLUGIN_ID, and DEFAULT_RTC_PROVIDER_DRIVER_ID", "built-in provider adapters for volcengine, aliyun, and tencent", "TypeScript provider package statuses standardize built-in root-public packages as root_public_reference_boundary and executable non-builtin packages as package_reference_boundary", "TypeScript runtime bridge baseline reference-baseline with official vendor SDK requirement required")),
        RtcLanguageWorkspaceCatalogEntry("flutter", "sdkwork-rtc-sdk-flutter", "Flutter", "rtc_sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is materialized now so the official language matrix stays explicit and verifiable. Future Flutter runtime bridge work must follow the same provider-adapter and capability standards as the TypeScript baseline.", listOf("provider metadata, capability matrix, and driver selection standards", "reserved Flutter language boundary with no runtime bridge claim in the current landing", "future Flutter runtime bridge work must follow the TypeScript baseline contract", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("rust", "sdkwork-rtc-sdk-rust", "Rust", "rtc_sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Rust standard boundary for provider metadata, selection, and future control-plane integration.", listOf("provider metadata and driver selection standards", "reserved Rust workspace boundary for control-plane expansion", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("java", "sdkwork-rtc-sdk-java", "Java", "com.sdkwork:rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Java standard boundary for provider metadata, driver selection, and future enterprise runtime integration.", listOf("provider metadata and driver selection standards", "reserved Java language boundary for future enterprise runtime integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("csharp", "sdkwork-rtc-sdk-csharp", "C#", "Sdkwork.Rtc.Sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved C# standard boundary for provider metadata, driver selection, and future desktop or server-side control integration.", listOf("provider metadata and driver selection standards", "reserved C# language boundary for desktop or server-side control integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("swift", "sdkwork-rtc-sdk-swift", "Swift", "RtcSdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Swift standard boundary for provider metadata, driver selection, and future iOS or macOS runtime bridge integration.", listOf("provider metadata and driver selection standards", "reserved Swift language boundary for iOS or macOS runtime bridge integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("kotlin", "sdkwork-rtc-sdk-kotlin", "Kotlin", "com.sdkwork:rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Kotlin standard boundary for provider metadata, driver selection, and future Android runtime bridge integration.", listOf("provider metadata and driver selection standards", "reserved Kotlin language boundary for Android runtime bridge integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("go", "sdkwork-rtc-sdk-go", "Go", "github.com/sdkwork/rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Go standard boundary for provider metadata, driver selection, and future control-plane tooling integration.", listOf("provider metadata and driver selection standards", "reserved Go language boundary for control-plane tooling integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
        RtcLanguageWorkspaceCatalogEntry("python", "sdkwork-rtc-sdk-python", "Python", "sdkwork-rtc-sdk", "reserved", true, false, "Reserved workspace skeleton", "This workspace is the reserved Python standard boundary for provider metadata, driver selection, and future automation or control-plane integration.", listOf("provider metadata and driver selection standards", "reserved Python language boundary for automation or control-plane integration", "no runtime bridge is claimed in the current landing", "code-level RtcStandardContract scaffold keeps provider-neutral core abstractions fixed before runtime bridge landing", "metadata scaffold fixes provider catalog, capability catalog, provider extension catalog, and provider selection skeleton boundaries before runtime bridge landing", "resolution scaffold fixes metadata-only driver manager, data source, and provider support boundaries before runtime bridge landing")),
    )

fun getRtcLanguageWorkspaceByLanguage(language: String): RtcLanguageWorkspaceCatalogEntry? =
        entries.firstOrNull { it.language == language }

}
